# Render Blueprint for Flask+Bokeh Portfolio Optimizer
# See: https://render.com/docs/yaml-spec for full reference
services:
  - type: web
    name: flaskbokeh-app
    env: python
    buildCommand: "uv pip install -r requirements.txt"
    startCommand: "gunicorn 'app:create_app()'"
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
